apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris-app
  labels:
    app: polaris-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polaris-app
  template:
    metadata:
      labels:
        app: polaris-app
    spec:
      containers:
        - name: polaris-app
          image: polaris-app:v0.1.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
