apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polaris-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: polaris-pipeline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_YOUR_GIT_URL
    targetRevision: main
    path: deploy/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: polaris-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
