name: Build, Scan and Push Docker Image

on:
  push:
    branches: ["main"]
  inputs:
    bump:
      description: "Which type of bump?"
      required: false
      default: "patch"
      type: choice
      options:
        - patch
        - minor
        - major
    deploy_env:
      description: "Which environment?"
      required: false
      default: "dev"
      type: choice
      options:
        - dev
        - prod

jobs:
  build-scan-patch:
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Done
        run: |
          echo "Done"
